name: deskpos
description: "EPOS Desktop App â€” offline-first POS system"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_riverpod: ^2.6.1

  # Database
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28

  # Immutable models
  freezed_annotation: ^2.4.4

  # Routing
  go_router: ^14.8.1

  # Utilities
  uuid: ^4.5.1
  crypto: ^3.0.6
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.14
  drift_dev: ^2.22.3
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  generate: true
